<?

$lang_list = Array("auto"=>"AUTO",
// "be"=>"Bielarus",
"bg"=>"Bulgarian",
// "bn"=>"Bengali",
"br"=>"Breton",
"ca"=>"Catalan",
"cs"=>"Czech",
"da"=>"Danish",
"de"=>"German",
"el"=>"Greek",
"en"=>"English",
// "eo"=>"Esperanto",
"es"=>"Spanish",
// "et"=>"Estonian",
"fa"=>"Persian",
// "fi"=>"Finnish",
"fo"=>"Faroese",
"fr"=>"French",
"ga"=>"Irish Gaelic",
"he"=>"Hebrew",
// "hi"=>"Hindi",
"hr"=>"Croatian",
// "hu"=>"Hungarian ",
"id"=>"Indonesian",
"is"=>"Icelandic",
"it"=>"Italian",
// "ku"=>"Kurdish",
// "la"=>"Latin",
// "lt"=>"Lithuanian",
// "lv"=>"Latvian ",
// "mi"=>"Maori",
// "mk"=>"Macedonian",
//"mn"=>"Mongolian",
//"ms"=>"Malay",
//"mt"=>"Maltese ",
"nl"=>"Flemish",
"no"=>"Norwegian",
// "pa"=>"Panjabi",
"pl"=>"Polish",
"pt"=>"Portuguese",
// "qu"=>"Quechua",
// "ro"=>"Romanian",
// "ro"=>"Romanian",
"ru"=>"Russian ",
// "sk"=>"Slovak",
// "sl"=>"Slovenian",
// "sr"=>"Serbian",
"sv"=>"Swedish",
//"sw"=>"Swahili",
//"ta"=>"Tamil",
//"tl"=>"Tagalog",
"tr"=>"Turkish",
"uk"=>"Ukrainian"
//"vi"=>"Vietnamese"
);

  
?>     
